### ISSUE TITLE
task `default` doesn't give a hint of its completion

### ISSUE THREAD

**Issue by DarkPark** [stringparser/gulp-runtime#24]
```js
var path = require('path'),
	gulp = require('gulp-runtime').create({repl: true}),
	glr  = require('gulp-livereload'),
	log  = require('./tasks/utils').log;


// enable colors in console
require('tty-colors');

// load tasks
require('./tasks/img');
require('./tasks/jade');
require('./tasks/lint');
require('./tasks/static');
require('./tasks/webpack');


// entry point
gulp.task('default', ['lint', 'img', 'jade', 'webpack', 'static'], function () {
	//gulp.watch(['./server/**/*.js'], ['apidoc']);

	// serve livereload
	glr.listen({quiet: true});

	// reload event
	gulp.watch(['./build/**/*.{html,js,css}']).on('change', function ( file ) {
		// report
		log('watch   '.bgCyan.black, 'reload ' + ('./' + path.relative(path.join(__dirname, '..'), file.path)).bold);
		// reload
		glr.changed(file);
	});
});
```

I get:
```
$ node gulpfile.js

/home/dp/Projects/fortnotes/client/node_modules/gulp-runtime/lib/proto.js:144
    throw error;
          ^
Error: task `default` doesn't give a hint of its completion
Meaning: it doesn't return nor uses a callback
Solution:
 - return a stream, promise or observable
 - use the callback that is passed as first argument
--
    at Runtime.task (~/Projects/fortnotes/client/node_modules/gulp-runtime/lib/proto.js:136:13)
    at Object.<anonymous> (/home/dp/Projects/fortnotes/client/gulpfile.js:31:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

but the `default` task shouldn't be completed
anyway a hint what I'm doing wrong would be nice :)

**Comment by stringparser** [comment]
Haha, yes I figured descriptive errors would be cool, like react does ;). 

You mean it shouldn't be completed because of the watcher right? But internally it should. All functions are composed aynchronously so if you don't return anything the only way to know you are done is using the callback passed as first argument. 

Maybe I can disable this warning if gets annoying. But for me its nice to make things clear.

**Comment by DarkPark** [comment]
full explanation is always good :)

dependent tasks definitely should be completed but watch task - I'm not so sure
anyway can you suggest how to rewrite this code to make it valid?

**Comment by stringparser** [comment]
Use the callback (`next`).
```js
gulp.task('default', ['lint', 'img', 'jade', 'webpack', 'static'], function (next) {
    //gulp.watch(['./server/**/*.js'], ['apidoc']);

    // serve livereload
    glr.listen({quiet: true});

    // reload event
    gulp.watch(['./build/**/*.{html,js,css}']).on('change', function ( file ) {
        // report
        log('watch   '.bgCyan.black, 'reload ' + ('./' + path.relative(path.join(__dirname, '..'), file.path)).bold);
        // reload
        glr.changed(file);
    });
    next();
});
```

And yes, I'm with you conceptually: the task hasn't ended. But if you want to dispatch the next function and you are running something in series for example, you should call it *when you are done doing stuff* on that function. 

Say you want start some watchers and after that reload the browser. That is fairly normal for the first run.
```js
var gulp = require('gulp-runtime').create();
var browserSync = require('browser-sync');

function watch(next){
  // watch stuff
  gulp.watch('app/**/*.js, );
}

// this will run one argument after another (strings or functions) waiting for each other to complete
// the default is not to wait, so not calling next is allright if you desire so
// on the case you are waiting if you don't use the callback, for this case, the browser will never reload
gulp.stack(watch, browserSync.reload, {wait: true})();
```

**Comment by stringparser** [comment]
By the way, the same thing you are doing with the default task you can achieve with the `stack` method and a function (I use [browser-sync](www.browsersync.io/docs/gulp) because it doesn't need the chrome extension to work) .

```js
var gulp = require('gulp-runtime').create();
var browserSync = require('browser-sync');

browserSync.init({
  server: {baseDir: './build'}
});

function watch(next){
   gulp.watch('./build/**/*.{html,js,css}', browserSync.reload);
   next();
}

gulp.stack(watch, 'lint img jade webpack static', {wait: true})();
```

In any case let me know if works for you, and we can close this one.

**Comment by DarkPark** [comment]
I've added `done` callback to the `default` task
```
gulp.task('default', ['lint', 'img', 'jade', 'less', 'webpack', 'static'], function ( done ) {
	// rebuild files on modification
	gulp.watch(['./js/**/*.js'], ['webpack:develop']);
	gulp.watch(['./jade/**/*.jade'], ['jade:develop']);
	gulp.watch(['./less/**/*.less'], ['less:develop']);

	// serve livereload
	glr.listen({quiet: true});

	// reload event
	gulp.watch(['./build/**/*.{html,js,css}']).on('change', function ( file ) {
		// report
		log('watch   '.bgCyan.black, 'reload ' + ('./' + path.relative(path.join(__dirname, '..'), file.path)).bold);
		// reload
		glr.changed(file);
	});

	done();
});
```
and now
```
$ node gulpfile.js
```
gives no output at all

**Comment by stringparser** [comment]
You should run it. 

```js
gulp.stack('default')();
```

There are no opinions about what should be run on start. Is up to you.

**Comment by DarkPark** [comment]
now it seems working
but imho in case you mimic by gulp everything should be exactly the same way as with gulp itself
no additional moves should be required
otherwise it makes everything very complicated

**Comment by stringparser** [comment]
Great. Aside of `stack` all the API is the same on front, yes, but is really different underneath. I somewhat agree with you, but if something is done automatically is should not run anything otherwise it would lead to things like #23. There you tried to use this for a cli and by doing choices instead of leaving them to whoever uses the code it made more problems than it solved.
